---
name: Build & Test
on: [push, pull_request] # yamllint disable-line rule:truthy

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        image: [alpine, centos, ubuntu, rhel]

    env:
      BASE: ${{ matrix.image }}
      KONG_DOCKER_TAG: kong-${{ matrix.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Test
      shell: script -q -e -c "bash {0}"
      run: |
        make test
    - name: Push RHEL
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      run: |
        make release-rhel
